// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmWDBhaBlF49Bb9ejxFdAdNzBVbNq7LnY',
    appId: '1:1048110479871:web:02c987f65d124ab1704fca',
    messagingSenderId: '1048110479871',
    projectId: 'hardman-firebase-app',
    authDomain: 'hardman-firebase-app.firebaseapp.com',
    storageBucket: 'hardman-firebase-app.appspot.com',
    measurementId: 'G-YY6XCFRYN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl6Xy6IZQQ-Vvl1WV36g5Pl8HNAbawasM',
    appId: '1:1048110479871:android:289c12084a4fab11704fca',
    messagingSenderId: '1048110479871',
    projectId: 'hardman-firebase-app',
    storageBucket: 'hardman-firebase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3GFPJPYaDJpYhkxWRiVRScbpPhCKDSxw',
    appId: '1:1048110479871:ios:de67ec1a6a6027d1704fca',
    messagingSenderId: '1048110479871',
    projectId: 'hardman-firebase-app',
    storageBucket: 'hardman-firebase-app.appspot.com',
    iosBundleId: 'com.example.projetoFlutter20241',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3GFPJPYaDJpYhkxWRiVRScbpPhCKDSxw',
    appId: '1:1048110479871:ios:f1fe0555ce628bfe704fca',
    messagingSenderId: '1048110479871',
    projectId: 'hardman-firebase-app',
    storageBucket: 'hardman-firebase-app.appspot.com',
    iosBundleId: 'com.example.projetoFlutter20241.RunnerTests',
  );
}
